language: python
sudo: true

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=daisyleenr
    - secure: b+UYfq2ofdHZgUlU0zfgPZIrAfEM/QNgOR9GP32XzrVYQRtT8dt75Oh0eYr/mnDzKNcy0MYGoMevSIPwZrTURGJp9qw/fRU40S6KVhG5AqT9JYIsFNBHt/K0IjtKpANXgSTp9LjslLLI6NTl8wJFcXcH0sq04yikq//zdLeSFbqX8Mv+l/NIk1EJnLWyQrJElLKwOejUEKOSW7UzEF+qpM6vbFBhJqHQkw7/UXFanDB3GfOLmlKPKjBbkERyloOs2lpJoq/uU/1UaBCg7lAi9OAauKmBEElVpf7aqwskUnlbtEvhmz0ZM+UYz2Mcn6l3RHFU8MBxox48NvJ1wnKF5VxwV4hoPQR2UenXy82YuPky99k1LyfqR5D552OLS75yjlvURfC4gHdGpBynx3sfmKoHZdqV8sxkrR9HFzS4ZIi1t6cx7yBnbYQykdLR2NOBlqSKZzD92lZPgE6tgTH+roxFSmA+XJQLu6/RkE7s3AvnWwvdqA+70BiVWE3YzL9G/DAcpFqwsHCZnxK3uIKDghD9gYzhu/muaAxyR2BUO+Bm5IJB5Xo5hx0CERDHVxt60MLTrTHZ7ooykPJDzRvAlKzio3Tq/G4miPBHA+JV5nLG5CdXICzdiQCocq2Vjcf6S80EPYci3whNBGaeLl6O5SlmDALRFDF6yMPkrUYsptQ=

before_install:
  - docker build -t daisyleenr/todo-frontend:$TRAVIS_BUILD_NUMBER -t daisyleenr/todo-frontend:latest .
  - docker run -d -p 3000:3000 daisyleenr/todo-frontend:latest
  - docker ps -a

install:
  - npm install

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

notifications:
  slack:
    secure: YVaUWSWl3PIFd/IeQc5ldRjYWroNWmPbJ0Xc/4kKa9lPFy1sK1nfMn+T2xRiRCG91MYRwCaxjUBJfC/FaJdWLVnG7dfatA8snjmhot2D0Q8/EILjc5xyzi3TDD3yReOdQlg23z6t4Xc4AjbXAqKSZQk83CrCQKWzVmd5hUzRxCbHqtGGL5VSc06ysnPN8qXAJiZqBH7ss9Bp4hQTD2itItMEQKhG5IdhZLqLxQI7B5EyaapnTNJJ43tmaqVkhuVSmY+JtPBlwUDjwvM0R67/jrmUCN9tBcjtPSBdufVoXkRO+H0kl1yEqNXzTfEVjSqVM0/c3PBVWCbMOnPaR3eaHgZu7VGDc7yUEw8AZogZwFHJoe4ubOq0bFzCIXVfaQTM7YeuaCf2wDLMLSoUvsPo+dg3jGYdu30J94aLLXYUC9PS393o5+JEyzj0SjPwDvIBHxWNaSRVBuP86W6EdJELC2SOR0P41vz+NhRABiU18XvKiPd6dZVYH888RiBYocpvF6OWoGIJuuFPzt3pZo14kpwrVk+GiB3aDP9yLyBHB10Qywg0XxflNLNbqtrJTdyzsfdZDefhXGFjSuG5BX3a+UHFQff7QmMkwqW2l4Lj4VcMDkiTo9XxOXphvb5eotuKDTC2OOuDkeVc74GNJuM43I8lgED7Rh3DlLQ0pMV6Rg4=
