version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: todolist
      MYSQL_PASSWORD: todolist
  todo-api-server:
    image: daisyleenr/todo-api-server:latest
    ports:
      - '5000:5000'
    restart: always
    environment:
      TODO_DB_USER: todolist
      TODO_DB_PASSWORD: todolist
      TODO_DB_NAME: todolist
      TODO_DB_HOST: db
      PYTHONPATH: .:$PYTHONPATH
    command: bash -c "alembic upgrade head && gunicorn --bind 0.0.0.0:5000 app:app"
  todo-frontend:
    image: daisyleenr/todo-frontend:latest
    ports:
      - '3000:3000'
    restart: always
volumes:
  db_data:
